
services:
  node1:
    build: .
    container_name: ds_node1
    environment:
      NODE_ID: "node1"
      PEERS: "http://node2:8000,http://node3:8000"
    command: ["python","-m","uvicorn","src.node.server:app","--host","0.0.0.0","--port","8000"]
    ports:
      - "8001:8000"
    volumes:
      - ./data/node1:/app/data

  node2:
    build: .
    container_name: ds_node2
    environment:
      NODE_ID: "node2"
      PEERS: "http://node1:8000,http://node3:8000"
    command: ["python","-m","uvicorn","src.node.server:app","--host","0.0.0.0","--port","8000"]
    ports:
      - "8002:8000"
    volumes:
      - ./data/node2:/app/data

  node3:
    build: .
    container_name: ds_node3
    environment:
      NODE_ID: "node3"
      PEERS: "http://node1:8000,http://node2:8000"
    command: ["python","-m","uvicorn","src.node.server:app","--host","0.0.0.0","--port","8000"]
    ports:
      - "8003:8000"
    volumes:
      - ./data/node3:/app/data
